name = "routesmith-admin"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "routesmith"
database_id = "25ef5dcc-2999-496a-83e8-39a616d4daaf"

[[r2_buckets]]
binding = "DATA_BUCKET"
bucket_name = "routesmith-data"
