/**
 * worker.ts — Cloudflare Worker entry point for the Routesmith REPORT module.
 *
 * Routes:
 *   POST /api/report/run     — Run the full pipeline, return HTML report
 *   POST /api/report/data    — Run the pipeline, return JSON dashboard data
 *   GET  /api/report/health  — Health check
 *
 * Environment bindings (wrangler.toml):
 *   REPORT_BUCKET  — R2 bucket for GPX files and reference lists
 *   DB             — D1 database
 *
 * Auth: Clerk JWT validation via the Authorization header.
 * The Clerk SDK for Cloudflare Workers handles this at the middleware layer
 * (see the separate auth Worker or middleware setup).
 *
 * Python reference: generate.py main() + Flask/FastAPI server layer
 */

import { runPipeline, type GpxSources } from './pipeline.js';
import { fetchReferenceListsFromR2 } from './referenceLists.js';
import { renderReport } from './renderer.js';
import type { TripInput } from './types.js';

// ============================================================================
// Environment type (generated by wrangler at build time; stub here)
// ============================================================================

export interface Env {
  REPORT_BUCKET: R2Bucket;
  DB: D1Database;
}

interface R2Bucket {
  get(key: string): Promise<{ text(): Promise<string>; arrayBuffer(): Promise<ArrayBuffer> } | null>;
}

interface D1Database {
  prepare(query: string): D1PreparedStatement;
}

interface D1PreparedStatement {
  bind(...args: unknown[]): D1PreparedStatement;
  first<T>(): Promise<T | null>;
  all<T>(): Promise<{ results: T[] }>;
}

// ============================================================================
// Request routing
// ============================================================================

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === '/api/report/health') {
      return new Response(JSON.stringify({ status: 'ok' }), {
        headers: { 'Content-Type': 'application/json' },
      });
    }

    if (request.method !== 'POST') {
      return new Response('Method Not Allowed', { status: 405 });
    }

    if (url.pathname === '/api/report/run') {
      return handleReportRun(request, env, 'html');
    }

    if (url.pathname === '/api/report/data') {
      return handleReportRun(request, env, 'json');
    }

    return new Response('Not Found', { status: 404 });
  },
};

// ============================================================================
// Report run handler
// ============================================================================

async function handleReportRun(
  request: Request,
  env: Env,
  format: 'html' | 'json',
): Promise<Response> {
  let body: {
    tripInput: TripInput;
    gpxSources: GpxSources;
  };

  try {
    body = await request.json();
  } catch {
    return jsonError('Invalid JSON request body', 400);
  }

  // Validate minimal required fields
  if (!body.tripInput?.startDate || !body.tripInput?.endDate || !body.tripInput?.owner) {
    return jsonError('tripInput must include startDate, endDate, and owner', 400);
  }

  // Load reference lists from R2
  let refLists;
  try {
    refLists = await fetchReferenceListsFromR2(env.REPORT_BUCKET as Parameters<typeof fetchReferenceListsFromR2>[0]);
  } catch (e) {
    return jsonError(`Failed to load reference lists: ${(e as Error).message}`, 500);
  }

  // Run pipeline
  let result;
  try {
    result = await runPipeline(body.tripInput, body.gpxSources, refLists);
  } catch (e) {
    return jsonError(`Pipeline error: ${(e as Error).message}`, 500);
  }

  if (format === 'json') {
    // Return structured data for the dashboard (map, charts, stats)
    // Sets and Maps are serialized to arrays for JSON transport
    return new Response(
      JSON.stringify({
        ownerStats: serializePlayerStats(result.ownerStats),
        allPlayerStats: result.allPlayerStats.map(serializePlayerStats),
        ruleResults: result.ruleResults.map(rr => ({
          rule: {
            id: rr.rule.id,
            displayName: rr.rule.displayName,
            description: rr.rule.description,
            severity: rr.rule.severity,
          },
          matches: rr.matches.map(m => ({
            waypoint: serializeWaypoint(m.waypoint),
            note: m.note,
          })),
        })),
        countiesData: {
          firstTime: [...result.countiesData.firstTime],
          previouslyFound: [...result.countiesData.previouslyFound],
          stateCoverage: result.countiesData.stateCoverage,
        },
        jasmerGridState: Object.fromEntries(result.jasmerGridState),
        fieldAvailability: result.fieldAvailability,
        warnings: result.warnings,
        diagnostics: result.diagnostics,
      }),
      { headers: { 'Content-Type': 'application/json' } },
    );
  }

  // Render HTML report
  const html = renderReport({
    tripInput: result.tripInput,
    ownerStats: result.ownerStats,
    allPlayerStats: result.allPlayerStats,
    ruleResults: result.ruleResults,
    countiesData: result.countiesData,
    jasmerGridState: result.jasmerGridState,
    ownerTripFinds: [],  // Pipeline could expose this; wire up if needed
    fieldAvailability: result.fieldAvailability,
  });

  return new Response(html, {
    headers: { 'Content-Type': 'text/html; charset=utf-8' },
  });
}

// ============================================================================
// Serialization helpers
// ============================================================================

function serializePlayerStats(p: import('./types.js').PlayerStats) {
  return {
    playerId: p.playerId,
    displayName: p.displayName,
    role: p.role,
    aggregate: p.aggregate,
    byDay: p.byDay.map(ds => ({
      dayDate: ds.dayDate.toISOString().slice(0, 10),
      finds: ds.finds,
      favoritePoints: ds.favoritePoints,
      counties: [...ds.counties],
      newCounties: ds.newCounties,
      byCacheType: ds.byCacheType,
      bestFind: ds.bestFind ? serializeWaypoint(ds.bestFind) : null,
      bestFindReason: ds.bestFindReason,
    })),
  };
}

function serializeWaypoint(w: import('./types.js').Waypoint) {
  return {
    gcCode: w.gcCode,
    name: w.name,
    cacheType: w.cacheType,
    lat: w.lat,
    lon: w.lon,
    county: w.county,
    state: w.state,
    country: w.country,
    favoritePoints: w.favoritePoints,
    difficulty: w.difficulty,
    terrain: w.terrain,
    findDate: w.findDate?.toISOString().slice(0, 10) ?? null,
    placementTime: w.placementTime?.toISOString() ?? null,
  };
}

// ============================================================================
// Error helper
// ============================================================================

function jsonError(message: string, status: number): Response {
  return new Response(JSON.stringify({ error: message }), {
    status,
    headers: { 'Content-Type': 'application/json' },
  });
}
